puts "================= trial_tcl.tcl ========================================="
puts "You just invoked a sample TCL script that demonstrates"
puts " the capability of DualCam-Companion to run custom commands."
puts "You can bind up to two custom commands to buttons Cust1 and Cust2"
puts "You can then change these button labels to reflect the new actions."
puts "A command can be either native OS executable or TCL script."
puts "To configure your own command, open Preferences window"
puts " and type full path of the executable program file"
puts " into the entry for '-custom_cmd_1' or '-custom_cmd_2'."
puts "In the case of TCL script the path could be relative."
puts "  The root for TCL-script paths is 'StereoPairs_TCL' directory"
puts "  of your DualCam-Companion installation."
puts "The path should use slash (/) as directory separator."
puts "The current 'trial_tcl.tcl' configured by default can serve as example."
puts "Clear the custom-command entry to have the custom button do nothing."
puts "To change label of the custom-command button, in Preferences window,"
puts " type the new label (up to 5 characters) into the entry"
puts " for '-custom_btn_1' or '-custom_btn_2'."
puts "You need to restart DualCam-Companion to see the label being changed."
puts "========================================================================="
puts "Working directory - as chosen by 'Folder' button:"
puts " '[pwd]'"
puts "========================================================================="
